name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: /home/user/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Install buildozer dependencies
        run: |
          /home/user/.venv/bin/pip install --upgrade "Cython<3.0" wheel pip setuptools

      - name: Build with Buildozer
        run: |
          export HOME=/home/user
          export PATH=/home/user/.venv/bin:$PATH
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Undertale-Life-After-APK
          path: ./bin/*.apk
